name: review-ms-dev

services:
  postgres-review:
    image: postgres:15
    container_name: serviya-postgres-review
    restart: unless-stopped
    environment:
      POSTGRES_USER: serviya
      POSTGRES_PASSWORD: change-me-only-in-local-dev
      POSTGRES_DB: review_ms
    ports:
      - "5437:5432"
    volumes:
      - pgdata-review:/var/lib/postgresql/data

volumes:
  pgdata-review:
