server:
  port: 8085

spring:
  application:
    name: technician-ms
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
  datasource:
    url: jdbc:postgresql://localhost:5436/serviya_technician
    username: serviya
    password: serviya_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/serviya
          jwk-set-uri: http://localhost:8089/realms/serviya/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  file:
    name: logs/technician-ms.log
