server:
  port: 8087

spring:
  application:
    name: notification-ms
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:18888}"
  datasource:
    url: jdbc:postgresql://localhost:5436/serviya_notification
    username: serviya
    password: serviya_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SERVIYA_KEYCLOAK_ISSUER_URI:http://localhost:8089/realms/serviya}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  file:
    name: logs/notification-ms.log
  level:
    root: INFO
    org.springframework.web: DEBUG
