server:
  port: 8083

spring:
  application:
    name: payment-ms
  datasource:
    url: jdbc:postgresql://localhost:5435/serviya_payment
    username: serviya
    password: serviya_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/serviya
          jwk-set-uri: http://localhost:8089/realms/serviya/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  file:
    name: logs/payment-ms.log
