server:
  port: 8084

spring:
  application:
    name: service-request-ms
  profiles:
    active: dev
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:18888}"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/serviya

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  file:
    name: logs/service-request-ms.log
  level:
    root: INFO
    com.serviya.servicerequest: DEBUG
    org.springframework.web: TRACE
    org.springframework.security: TRACE
