CREATE TABLE IF NOT EXISTS categorias_servicio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(50) NOT NULL,
  nombre VARCHAR(100) NOT NULL,
  descripcion VARCHAR(500),
  icono VARCHAR(50) NOT NULL DEFAULT 'wrench',
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE categorias_servicio ADD COLUMN IF NOT EXISTS icono VARCHAR(50) NOT NULL DEFAULT 'wrench';

ALTER TABLE categorias_servicio DROP CONSTRAINT IF EXISTS uk_categorias_servicio_codigo;
ALTER TABLE categorias_servicio ADD CONSTRAINT uk_categorias_servicio_codigo UNIQUE (codigo);

CREATE TABLE IF NOT EXISTS servicios_catalogo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria_id BIGINT NOT NULL,
  codigo VARCHAR(50) NOT NULL,
  nombre VARCHAR(150) NOT NULL,
  descripcion VARCHAR(500),
  precio_base_referencial NUMERIC(12, 2),
  requiere_foto BOOLEAN DEFAULT FALSE,
  image_url VARCHAR(500),
  duracion_estimada VARCHAR(50),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE servicios_catalogo DROP CONSTRAINT IF EXISTS uk_servicios_catalogo_codigo;
ALTER TABLE servicios_catalogo ADD CONSTRAINT uk_servicios_catalogo_codigo UNIQUE (codigo);

ALTER TABLE servicios_catalogo DROP CONSTRAINT IF EXISTS fk_servicios_catalogo_categoria;
ALTER TABLE servicios_catalogo ADD CONSTRAINT fk_servicios_catalogo_categoria FOREIGN KEY (categoria_id) REFERENCES categorias_servicio (id);

CREATE INDEX IF NOT EXISTS idx_servicios_catalogo_categoria_id
  ON servicios_catalogo (categoria_id);

ALTER TABLE servicios_catalogo ADD COLUMN IF NOT EXISTS image_url VARCHAR(500);
ALTER TABLE servicios_catalogo ADD COLUMN IF NOT EXISTS duracion_estimada VARCHAR(50);
ALTER TABLE servicios_catalogo ADD COLUMN IF NOT EXISTS tipo_cobro VARCHAR(20);
ALTER TABLE servicios_catalogo ADD COLUMN IF NOT EXISTS modalidad_evaluacion VARCHAR(20);

ALTER TABLE IF EXISTS solicitudes_servicio DROP CONSTRAINT IF EXISTS solicitudes_servicio_estado_solicitud_check;
ALTER TABLE IF EXISTS solicitudes_servicio ADD CONSTRAINT solicitudes_servicio_estado_solicitud_check
  CHECK (estado_solicitud IN (
    'ESPERANDO_PAGO_VISITA',
    'PENDIENTE_EVALUACION',
    'COTIZADO_ESPERANDO_PAGO',
    'PAGADO_BUSCANDO_TECNICO',
    'TECNICO_ASIGNADO',
    'EN_PROCESO',
    'COMPLETADO',
    'CANCELADO',
    'REEMBOLSADO'
  ));
