CREATE TABLE IF NOT EXISTS outbox_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aggregate_id VARCHAR(36) NOT NULL,
  event_type VARCHAR(255) NOT NULL,
  payload TEXT NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  sent_at TIMESTAMP WITH TIME ZONE,
  retry_count INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS ix_outbox_events_status_created_at
  ON outbox_events (status, created_at);

CREATE TABLE IF NOT EXISTS inbox_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id VARCHAR(36) NOT NULL,
  event_type VARCHAR(255) NOT NULL,
  consumer_service VARCHAR(120) NOT NULL,
  processed_at TIMESTAMP WITH TIME ZONE,
  status VARCHAR(32) NOT NULL,
  CONSTRAINT uk_inbox_events_event_id UNIQUE (event_id)
);

CREATE INDEX IF NOT EXISTS ix_inbox_events_status
  ON inbox_events (status);

CREATE TABLE IF NOT EXISTS clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR(36) NOT NULL,
  identity_subject VARCHAR(120) NOT NULL,
  first_name VARCHAR(120) NOT NULL,
  last_name VARCHAR(120) NOT NULL,
  email_contact VARCHAR(180) NOT NULL,
  phone VARCHAR(40) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT uk_clients_public_id UNIQUE (public_id),
  CONSTRAINT uk_clients_identity_subject UNIQUE (identity_subject)
);

CREATE TABLE IF NOT EXISTS client_addresses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR(36) NOT NULL,
  client_id BIGINT NOT NULL,
  department VARCHAR(120) NOT NULL,
  province VARCHAR(120) NOT NULL,
  district VARCHAR(120) NOT NULL,
  address_line VARCHAR(240) NOT NULL,
  reference VARCHAR(240),
  is_primary BOOLEAN NOT NULL,
  active BOOLEAN NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT uk_client_addresses_public_id UNIQUE (public_id)
);

CREATE INDEX IF NOT EXISTS ix_client_addresses_client_active
  ON client_addresses (client_id, active);

CREATE TABLE IF NOT EXISTS client_preferences (
  client_id BIGINT PRIMARY KEY,
  language VARCHAR(16) NOT NULL,
  timezone VARCHAR(80) NOT NULL,
  notifications_enabled BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS client_consents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL,
  consent_type VARCHAR(80) NOT NULL,
  document_version VARCHAR(40) NOT NULL,
  accepted BOOLEAN NOT NULL,
  accepted_at TIMESTAMP WITH TIME ZONE NOT NULL,
  ip_hash VARCHAR(128),
  user_agent VARCHAR(240)
);

CREATE INDEX IF NOT EXISTS ix_client_consents_client
  ON client_consents (client_id, consent_type);
