name: assignment-ms-dev

services:
  postgres-assignment:
    image: postgres:15
    container_name: serviya-postgres-assignment
    restart: unless-stopped
    environment:
      POSTGRES_USER: serviya
      POSTGRES_PASSWORD: change-me-only-in-local-dev
      POSTGRES_DB: assignment_ms
    ports:
      - "5440:5432"
    volumes:
      - pgdata-assignment:/var/lib/postgresql/data

volumes:
  pgdata-assignment:
