spring:
  application:
    name: notification-ms
  datasource:
    url: ${SERVIYA_DATASOURCE_URL:jdbc:postgresql://localhost:5438/notification_ms}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
