spring:
  application:
    name: review-ms
  datasource:
    url: ${SERVIYA_DATASOURCE_URL:jdbc:postgresql://localhost:5437/review_ms}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
