spring:
  application:
    name: technician-ms
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
  datasource:
    url: ${SERVIYA_DATASOURCE_URL:jdbc:postgresql://localhost:5433/technician_ms}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
